# Generated by Django 2.0.7 on 2018-08-12 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortify',
            name='clickCount',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
    ]
